# Generated by Django 4.2.30 on 2026-06-24 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_text', models.TextField(help_text='The chunk of text passed to the TTS engine')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='generated_audio/')),
                ('speaker', models.CharField(max_length=100)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('duration', models.FloatField(blank=True, help_text='Length of generated audio in seconds', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('PROCESSING', 'Synthesizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Title of the documentary project', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional project summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='tts_models/en/vctk/vits', max_length=150)),
                ('speaker_id', models.CharField(default='p266', max_length=100)),
                ('speed', models.FloatField(default=1.0, help_text='Speech speed modifier (0.5 to 2.0)')),
                ('pitch', models.FloatField(default=1.0, help_text='Speech pitch modifier (if supported by backend)')),
                ('output_format', models.CharField(default='wav', max_length=10)),
                ('output_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_content', models.TextField(blank=True, help_text='Captured console output or traceback logs', null=True)),
                ('processing_time_seconds', models.FloatField(default=0.0, help_text='Total processing time in seconds')),
                ('system_details', models.CharField(blank=True, help_text='CPU/GPU usage statistics during run', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.generatedaudio')),
            ],
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_audios', to='projects.project'),
        ),
    ]
